mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bode.docsys.entity
  #全局配置
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

redis:
  host: 127.0.0.1
  port: 6379


spring:
  application:
    name: TheSystem
  datasource:
    url: jdbc:mysql://localhost:3306/bodesystem?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

token:
  # 30*60s
  redisExpireTime: 1800
  expireTime: 300